# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c12281ef52b6e0136295c6a41dc730029d760fcbbe952ecd6128b5f92cdf75ee2d188fd99e029370583f000384a2ef59ddda26162252bd7fca4a77a0b696167

test:
  secret_key_base: cbf9f99b2365d639c787c1c6e89ffa2f86a55fe23ed2cb4a53f992c96400885227dad08f4ffd2a00193efa6c43343c77af10de27e56e8a2d3da5eb1351775793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
